version: '3'
services:
  mysql:
    platform: linux/x86_64    # 추가된 라인 M1 에서만 추가
    container_name: spring_batch
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "spring_batch"
      MYSQL_ROOT_PASSWORD: "password1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
